config/routes.rb
Rails.application.routes.draw do
  # this rule maps requests for the URL /static_pages/home to the home action in the Static Pages Controller
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  resources :users


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # the home action is empty, so all visiting /static_pages/home does is render the view
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
     

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.bg-body-tertiary
  .container
    = link_to "Cat Cafe", root_path, id: "logo", class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNav", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", href: root_path} Home
        %li.nav-item
          %a.nav-link{href: help_path} Help
        %li.nav-item
          %a.nav-link{href: about_path} About
      %ul.navbar-nav.ms-auto
        %li.nav-item
          %a.nav-link{href: "#"} Log In

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Cat Cafe"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags

    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    
  %body
    = render 'layouts/header'      
    .container
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/static_pages/about.html.haml
- provide(:title, "About")
%title 
  = yield(:title)
%h1 About Cat Cafe 
%p Here at Cat Cafe, all are welcome to share and exchange ideas, big or small! 
= link_to "Rails Tutorial", "https://www.railstutorial.org/"  

app/views/static_pages/contact.html.haml
- provide(:title, "Contact")
%title
  = yield(:title)
%h1
  Contact 
%p Contact the Ruby on Rails Tutorial about the sample add at the 
= link_to "Rails Tutorial", "https://www.railstutorial.org/contact"

app/views/static_pages/help.html.haml
- provide(:title, "Help")
%title
  = yield(:title)
%h1 Help
%p Having trouble with the platform? Help is on the way! 

app/views/static_pages/home.html.haml
- provide(:title, "Home")
%title
  = yield(:title)
.center.jumbotron
  = image_tag 'Lucky-cat.svg', alt: "Cute kitten", style: 'width: 200px; height: auto;'
  %h1 Cat Cafe
  %p
    This is the home page for Cat Cafe!
  %p
    An online platform for idea sharing <3
  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"
  

app/views/users/new.html.haml
- provide(:title, "Sign up")
%title
  = yield(:title)
%h1 Sign up
.row 
  .col-md-6.col-md-offset-3 
    = form_with(model: @user, local: true) do |f|
      = f.label :name
      = f.text_field :name
      = f.label :email 
      = f.email_field :email 
      = f.label :password 
      = f.password_field :password 
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row 
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.name